### ISSUE TITLE
Setup Kanban Board for the Group Capstone Project

### ISSUE THREAD

**Issue by Elhambasir** [sumon766/frontend-doctor-appointment#11]
## Description

![front-end-kanaban-board](https://github.com/sumon766/frontend-doctor-appointment/assets/108110651/13db5c81-cee7-4479-a526-14d8f7f88461)

Link to the [frontend project](https://github.com/users/sumon766/projects/3).
Link to the [backend project](https://github.com/users/sumon766/projects/4).

Group members:
We are group of four:
1. @serengia 
2. @Lul-Abdifan 
3. @Elhambasir 
4. @sumon766

**Comment by Meltrust** [comment]
Hi @Elhambasir,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All reqs have been met ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
